# Site settings
title: 'Heath Dutton'
description: 'Developer / CSM'
url: 'http://heathdutton.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'heath dutton'
  email: heathdutton@gmail.com
  linkedin_username: heathdutton
  github_username: heathdutton
  drupal_username: heathdutton
  twitter_username: heathdutton
  # facebook_username: heathadutton

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
